Accounts/urls.py
from .views import vendor_reg_view, user_login_view, customer_reg_view, user_logout_view, must_auth
from django.urls import path

app_name = 'user'

urlpatterns = [
    path('v_reg/', vendor_reg_view, name='v_reg'),
    path('c_reg/', customer_reg_view, name='c_reg'),
    # path('v_login/', vendor_login_view, name='v_login'),
    path('login/', user_login_view, name="login"),
    path('logout/', user_logout_view, name='logout'),
    path('must_auth/', must_auth, name='must_auth')
]

E_commerce/urls.py
from re import template
from django.contrib import admin
from django.urls import path, include, reverse_lazy,re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from store.views import (
    delete_order_item, home_page, ContactView,
    ShopView, product_details,
    cart, checkout,
    add_product_view, quantity_increment,
    quantity_decrement, delete_order_item,
    # load_cities,
    no_cart, all_reviews,
    no_checkout, add_to_cart,
    get_product_queryset, review,
    vendor_dashboard, delete_product,
    vendor_product_detail, update_product,
    customer_dashboard, just_arrived,
    add_to_wishlist, remove_from_wishlist,
    wishlist, remove_from_wishlist_view,
    men_category,women_category,
    male_children_category, female_children_category,
    no_search, billing_address,
    make_payment, shop
    )
urlpatterns = [
    path('admin/', admin.site.urls),
    path("paystack", include(("paystack.frameworks.django.urls", 'paystack'),namespace='paystack')),
    path('', home_page, name='home'),
    path('shop/', shop, name='shop'),
    path('make-payment/', make_payment, name='make-payment'),
    path('add_to_cart/<product_id>/', add_to_cart, name='add_to_cart'),
    path('just_arrived_products/', just_arrived, name='just_arrived'),
    path('add_to_wishlist/<product_id>/', add_to_wishlist, name='add_to_wishlist'),
    path('remove_from_wishlist/<product_id>/', remove_from_wishlist, name='remove_from_wishlist'),
    # path('shop/', ShopDetailView.as_view(), name='shop'),
    path('<product_id>/product_details/', product_details, name='product_details'),
    path('wishlist/', wishlist, name='wishlist'),
    path('remove_from_wishlist_view/<product_id>', remove_from_wishlist_view, name='remove_from_wishlist_view'),
    path('search/', get_product_queryset, name="search"),
    path('no-search/', no_search, name="no_search"),
    path('<product_id>/reviews/', review, name="review"),
    path('vendor_dashboard/', vendor_dashboard, name='v_dashboard'),
    path('customer_dashboard/', customer_dashboard, name='c_dashboard'),
    path('billing_address/<transaction_id>/', billing_address, name='billing_address'),
    path('<product_id>/vendor_product_details/', vendor_product_detail, name='v_product_details'),
    path('<product_id>/update_product', update_product, name="update_product"),
    path('<product_id>/delete_product', delete_product, name="delete_product"),
    path('cart/', cart, name='cart'),
    path('all_reviews/<product_id>/', all_reviews, name='all_reviews'),
    path('men_category/', men_category, name='men_category'),
    path('women_category/', women_category, name='women_category'),
    path('male_children_category/', male_children_category, name='male_children_category'),
    path('female_children_category/', female_children_category, name='female_children_category'),
    path('cart/<item_id>/increment/', quantity_increment, name='q_incr'),
    path('cart/<item_id>/decrement/', quantity_decrement, name='q_decr'),
    path('cart/<item_id>/delete/', delete_order_item, name='del_item'),
    path('checkout/', checkout, name='checkout'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('add-product/', add_product_view, name='add-product'),
    path('users/', include('Accounts.urls')),
    # re_path(r'^update_item/$', updateItem, name='update_item'),
    path('no_cart/', no_cart, name='no_cart'),
    path('no_checkout', no_checkout, name='no_checkout'),
    # path('ajax/load-cities/', load_cities, name='ajax_load_cities'),

    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name="password/password_change_done.html"), name="password_change_done"),

    # path('password_change/', auth_views.PasswordChangeView.as_view(template_name='password/password_change.html'), name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name="password/password_reset_done.html"), name="password_reset_done"),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password/password_reset_complete.html'), name="password_reset_complete"),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='password/password_reset_form.html', 
        success_url = reverse_lazy('password_reset_complete'),
    ), name="password_reset_confirm"),    

    path('password_reset/', auth_views.PasswordResetView.as_view(
        template_name='password/password_reset.html',
        email_template_name='password/password_reset_email.html',
        subject_template_name='password/password_reset_subject.txt',
        success_url = reverse_lazy('password_reset_done'),
    ), name='password_reset'),
    
]




# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

paystack/frameworks/django/urls.py
import django

version = django.get_version().split(".")
if int(version[0]) >= 2:
    from django.urls import re_path as url
else:
    from django.conf.urls import url

from django.views.decorators.csrf import csrf_exempt

from . import settings
from . import views

urlpatterns = [
    url(
        r"^verify-payment/(?P<order>[\w.@+-]+)/$",
        views.verify_payment,
        name="verify_payment",
    ),
    url(
        r"^failed-verification/(?P<order_id>[\w.@+-]+)/$",
        views.failure_redirect_view,
        name="failed_verification",
    ),
    url(
        r"^successful-verification/(?P<order_id>[\w.@+-]+)/$",
        views.success_redirect_view,
        name="successful_verification",
    ),
    url(
        r"^failed-page/$",
        views.TemplateView.as_view(template_name="paystack/failed-page.html"),
        name="failed_page",
    ),
    url(
        r"^success-page/$",
        views.TemplateView.as_view(template_name="paystack/success-page.html"),
        name="success_page",
    ),
    url(r"^webhook/$", csrf_exempt(views.webhook_view), name="webhook"),
]

store/models.py
import uuid
from django.conf import settings
from phonenumber_field.modelfields import PhoneNumberField
from django.db import models
from django.dispatch import receiver
from django.utils import timezone
from django.utils.text import slugify
from django.db.models.signals import pre_save, post_delete
from django.dispatch import receiver
from Accounts.models import Customer, User
from django_countries.fields import CountryField
from django.core.validators import MinValueValidator, MaxValueValidator
from decimal import Decimal

def upload_location(instance, filename):
    return f'product/{str(instance.seller)}/{str(instance.product_name)}/{str(instance.product_id)}-{filename}'

PERCENTAGE_VALIDATOR = [MinValueValidator(0), MaxValueValidator(100)]
class Product(models.Model):
    """Creates these fields in the database for a new product."""

    seller =                    models.ForeignKey(settings.AUTH_USER_MODEL,on_delete = models.CASCADE, null=True, blank=True)
    product_id =                models.UUIDField(primary_key=True, default=uuid.uuid4, editable=True, verbose_name="product's id", blank=True)
    product_name =              models.CharField(max_length=128, verbose_name="product's name", null=False, blank=False)
    product_price =             models.DecimalField(max_digits=255, decimal_places=2, verbose_name="product's price", null=False, blank=False)
    product_sizes =             models.CharField(max_length=255, null=False, blank=False, verbose_name="product sizes")
    number_available =          models.IntegerField(verbose_name='number available', blank=False, null=False)
    product_colors =            models.CharField(max_length=255,verbose_name="product's colors", blank=False, null=False)
    product_categories =            models.CharField(max_length=255,verbose_name="product's categories", blank=False, null=False)
    # product_category =          models.ManyToManyField(Category)
    # product_weight =            models.FloatField(verbose_name="product's weight", null=False, blank=False)
    product_image1 =            models.ImageField(upload_to=upload_location, null=True, blank=False, verbose_name='product image 1')
    product_image2 =            models.ImageField(upload_to=upload_location, null=True, blank=True, verbose_name='product image 2')
    product_image3 =            models.ImageField(upload_to=upload_location, null=True, blank=True, verbose_name='product image 3')
    product_description =       models.TextField(max_length=1000, verbose_name="product's description", blank=False)
    slug =                      models.SlugField(blank=True, unique=True, max_length=255)
    num_of_reviews =            models.IntegerField(blank=True, null=True)
    average_rating =            models.IntegerField(blank=True, null=True)
    num_of_ratings =            models.IntegerField(blank=True, null=True)
    num_of_visits =             models.IntegerField(blank=True, null=True, default=0)
    last_visit =                models.DateTimeField(auto_now=True, blank=True, null=True)
    date_added =                models.DateTimeField(auto_now_add=True, null=True, blank=True)
    discount =                  models.DecimalField(max_digits=3, decimal_places=0, default=Decimal(0), validators=PERCENTAGE_VALIDATOR, null=True, blank=False)
    customer_viewed_by =        models.ForeignKey(Customer, related_name='related_secondary_user', on_delete=models.CASCADE, null=True, blank=True)
    def __str__(self):
        return self.product_name

    @property
    def get_discount_price(self):
        discount_price = self.product_price - (self.product_price * self.discount)/100
        return discount_price

class UsersRecentlyViewedProduct(models.Model):
    customer =          models.ForeignKey(Customer, on_delete=models.CASCADE, null=True)
    product =       models.ForeignKey(Product, on_delete=models.CASCADE, null=True)
    time_visited =  models.DateTimeField(blank=True, null=True)

    def __str__(self):
        if self.customer is not None:
            return self.customer.fullname
        else:
            return ''

def pre_save_product_receiver(sender, instance, **kwargs):
    """Checks if a product has a slug, if not it creates one before committing to the database"""
    if not instance.slug:
        instance.slug = slugify(f"{instance.seller}" + '-' + f"{instance.product_name}" + '-' + f"{instance.product_id}")
pre_save.connect(pre_save_product_receiver, sender=Product)


@receiver(post_delete, sender=Product)
def submission_delete(sender, instance, **kwargs):
    """Deletes the image(s) of a product when the correlating product is deleted"""
    instance.product_image1.delete(False)
    instance.product_image2.delete(False)
    instance.product_image3.delete(False)


class Order(models.Model):
    transaction_id =        models.UUIDField(default=uuid.uuid4, editable=True, null=True)
    customer =              models.ForeignKey(Customer, null=True, blank=True, on_delete=models.CASCADE)
    date_ordered =          models.DateTimeField(auto_now_add=True)
    complete =              models.BooleanField(default=False)
    total_order_price =     models.DecimalField(max_digits=255, decimal_places=2, null=True)


    @property
    def get_cart_total(self):
        orderitems =    self.orderitem_set.all()
        total =         sum([item.get_items_price for item in orderitems])
        return total

    @get_cart_total.setter
    def get_cart_total(self, value):
        pass

    @property
    def get_cart_items(self):
        orderitems =          self.orderitem_set.all()
        items_total =         sum([item.quantity for item in orderitems])
        return items_total

    # @property
    # def total_order_price(self):
    #     orderitems =    self.orderitem_set.all()
    #     total_order =   sum([]item.quantity)
    @property
    def shipping(self):
        shipping = True
        return shipping

    def __str__(self):
        return str(self.transaction_id)


class Review(models.Model):
    product =     models.ForeignKey(Product, on_delete=models.CASCADE, null=True)
    user =        models.ForeignKey(Customer, on_delete=models.CASCADE, null=False)
    user_review = models.TextField(max_length=1000, blank=True, null=True)
    rating =      models.IntegerField(null=True, default=0, blank=True)
    created_on =  models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return f"{self.user.fullname}'s review"


class OrderItem(models.Model):
    item_id =               models.UUIDField(default=uuid.uuid4, editable=True, null=True, unique=True)
    order =                 models.ForeignKey(Order, on_delete=models.CASCADE, null=True)
    product =               models.ForeignKey(Product, on_delete=models.CASCADE, null=True)
    date_added =            models.DateTimeField(auto_now_add=True)
    quantity =              models.IntegerField(null=True, blank=True, default=0)
    size =                 models.CharField(max_length=255, null=True, blank=False)
    color =                 models.CharField(max_length=255, null=True, blank=False)
    
    @property
    def ordered_product_color(self):
        return self.product.product_colors.split(',')
    # p = self.OrderItem()
    # opc = p.ordered_product_color()
    # for color in opc:
    #     COLOR_CHOICES.append((color, color))
    @property
    def ordered_product_size(self):
        return self.product.product_sizes.split(',')
    

    @property
    def get_items_price(self):
        total_item_price = self.quantity * self.product.get_discount_price
        return total_item_price

    @get_items_price.setter
    def get_items_price(self, value):
        # self._location = value
        pass


class WishList(models.Model):
    item_id =           models.UUIDField(default=uuid.uuid4, editable=True, null=True, unique=True)
    customer =          models.ForeignKey(Customer, on_delete=models.CASCADE, null=True)
    product =           models.ForeignKey(Product, on_delete=models.CASCADE, null=True)
    date_added =        models.DateTimeField(auto_now_add=True)
    heart_val =         models.BooleanField(default=False)
    wish_item_counter = models.IntegerField(null=True, blank=False)

    def __str__(self):
        return f'{self.customer.username}-{self.product.product_name}'


class BillingAddress(models.Model):
    customer =          models.ForeignKey(Customer, on_delete=models.CASCADE, null=True, blank=True)
    fullname =         models.CharField(max_length=255, null=False, default="", blank=True)
    country =           CountryField(max_length=255, null=False, blank=False)
    phone_num1 =        PhoneNumberField(null=True, blank=True, verbose_name="Phone No 1", region="")
    email =             models.EmailField(max_length=128, null=False, default="", blank=False)
    address =          models.CharField(max_length=512, null=False, default="", blank=True)
    order =             models.ForeignKey(Order, on_delete=models.CASCADE, null=True, blank=True)
    city =              models.CharField(null=False, max_length=255, default="", blank=False)
    state =             models.CharField(null=False, max_length=255, blank=False)
    zipcode =           models.IntegerField(null=False, blank=False)
    date_added =        models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f' {self.fullname}, {self.customer.username}, ({self.address})'

store/templates/store/all_reviews.html
{% extends 'base.html' %}
{% block title %}All Reviews{% endblock title %}
{% block content %}
<div class="m-2 p-3">
    <div class="justify-content-center border-secondary mb-4">
        <h2 class="text-center">Verified Reviews({{reviews_counter}})✅</h2>
    </div>
    {% include '../snippets/reviews_snippet.html' with reviews=all_reviews %}
</div>
{% endblock content %}

store/templates/store/checkout.html
{% extends 'base.html' %}
{% block title %}Checkout{% endblock title %}
{% block content %}

    {% include 'messages.html' %}
    <div class="mx-3 ml-5">
        {% for field in billing_form %}
        {% for error in field.errors %}
            <p style="color: red;">{{field.label_tag}}  {{ error }}</p>
        {% endfor %}
        {% endfor %}
    </div>
    <div class="container-fluid bg-secondary mb-5">
        <div class="d-flex flex-column align-items-center justify-content-center" style="min-height: 200px">
            <h1 class="font-weight-semi-bold text-uppercase mb-3">Checkout</h1>
            <div class="d-inline-flex">
                <p class="m-0"><a href="{% url 'home' %}">Home</a></p>
                <p class="m-0 px-2">-</p>
                <p class="m-0">Checkout</p>
            </div>
        </div>
    </div>
    
    <!-- Checkout Start -->
    <div class="container-fluid pt-5">
        <div class="row px-xl-5">
            <div class="col-lg-8">
                <form action="{% url 'checkout' %}" method="post">
                    {% csrf_token %}
                    <!-- <script src="https://js.paystack.co/v1/inline.js"></script> -->
                    <div class="mb-4">
                        <h4 class="font-weight-semi-bold mb-4">Billing Address</h4>
                        <div class="row">
                            <div class="col-md-6 form-group">
                                <label>FullName</label>
                                <input class="form-control" name="fullname" id="id_fullname" type="text" placeholder="John" required value="{{request.user.fullname}}">
                            </div>
                            <div class="col-md-6 form-group">
                                <label>E-mail</label>
                                <input class="form-control" type="email" name="email" id="id_email" placeholder="example@email.com" required value="{{request.user.email}}">
                            </div>
                            <div class="col-md-6 form-group">
                                <label>Mobile No 1</label>
                                <input class="form-control" type="tel" name="phone_num1" id="id_phone_num1" placeholder="+123 456 789" required>
                            </div>
                            <!-- <div class="col-md-6 form-group">
                                <label>Mobile No 2</label>
                                <input class="form-control" type="tel" name="phone_num2" id="id_phone_num2" placeholder="+123 456 789" required value="{{request.user.second_phone_num}}">
                            </div> -->
                            <div class="col-md-6 form-group">
                                <label>Address Line 1</label>
                                <input class="form-control" type="text" name="address" id="id_address" placeholder="123 Street" required value="{{request.user.address}}">
                            </div>
                            <div class="col-md-6 form-group">
                                <label>Country</label>
                                {{ billing_form.country }}
                                <!-- <select class="custom-select">
                                    <option selected>United States</option>
                                    <option>Afghanistan</option>
                                    <option>Albania</option>
                                    <option>Algeria</option>
                                </select> -->
                            </div>
                            <div class="col-md-6 form-group">
                                <label>City</label>
                                <input class="form-control" type="text" name="city" id="id_city" required>
                            </div>
                            <div class="col-md-6 form-group">
                                <label>State</label>
                                <input class="form-control" type="text" name="state" id="id_state" required>
                            </div>
                            <div class="col-md-6 form-group">
                                <label>ZIP Code</label>
                                <input class="form-control" type="text" name="zipcode" id="id_zipcode" placeholder="123" required>
                            </div>
                            <!-- <div class="mt-5 h4">
                                <span class="font-weight-semi-bold">Total Amount: </span>
                                <span class="h5">#{{ total }}</span>
                            </div> -->
                            <!-- <div class="col-md-12 form-group">
                                <div class="custom-control custom-checkbox">
                                    <input type="checkbox" class="custom-control-input" id="newaccount">
                                    <label class="custom-control-label" for="newaccount">Create an account</label>
                                </div>
                            </div>
                            <div class="col-md-12 form-group">
                                <div class="custom-control custom-checkbox">
                                    <input type="checkbox" class="custom-control-input" id="shipto">
                                    <label class="custom-control-label" for="shipto"  data-toggle="collapse" data-target="#shipping-address">Ship to different address</label>
                                </div>
                            </div> -->
                        </div>
                    </div>
                    <input type="submit" id="submit-form" style="display:none;" />
                </form>

            </div>
            <div class="col-lg-4">
                <div class="card border-secondary mb-5">
                    <div class="card-header bg-secondary border-0">
                        <h4 class="font-weight-semi-bold m-0">Order Total</h4>
                        <h4 class="font-weight-semi-bold m-0">Make Payment (in Naira)</h4>
                    </div>
                    <div class="card-body font-weight-semi-bold">
                        <h5 class="font-weight-medium mb-3">Products</h5>
                        {% for item in items %}
                        {% if item.quantity > 0 %}
                        <div class="d-flex justify-content-between text-dark">
                            <p>{{ item.product.product_name }}</p>
                            {% if item.product.discount == 0 %}
                            <span>(#{{ item.product.product_price }}x{{ item.quantity }})({{item.color|upper}})({{item.size|upper}})</span>
                            {% else %}
                            <span>(#{{ item.product.get_discount_price }}x{{ item.quantity }})({{item.color|upper}})({{item.size|upper}})</span>
                            {% endif %}
                        </div>
                        {% endif %}
                        {% endfor %}
                        <!-- <div class="d-flex justify-content-between">
                            <p>Colorful Stylish Shirt 2</p>
                            <p>#150</p>
                        </div>
                        <div class="d-flex justify-content-between">
                            <p>Colorful Stylish Shirt 3</p>
                            <p>#150</p>
                        </div> -->
                        <hr class="mt-0">
                        <div class="d-flex justify-content-between mb-3 pt-1">
                            <h6 class="font-weight-medium">Subtotal</h6>
                            <h6 class="font-weight-medium">#{{ sub_total }}</h6>
                        </div>
                        <div class="d-flex justify-content-between">
                            <h6 class="font-weight-medium">Shipping</h6>
                            <h6 class="font-weight-medium">#100</h6>
                        </div>
                    </div>
                    <div class="card-footer border-secondary bg-transparent">
                        <div class="d-flex justify-content-between mt-2">
                            <h5 class="font-weight-bold">Total</h5>
                            <h5 class="font-weight-bold">#{{ total }}</h5>
                        </div>
                    </div>
                </div>
                <div class="card border-secondary mb-5">
                    <div class="card-header bg-secondary border-0">
                        <h4 class="font-weight-semi-bold m-0">Payment Method</h4>
                        <p class="mt-3 font-weight-bold text-dark">Paystack</p>
                    </div>
                    <div class="card-footer border-secondary bg-transparent">
                        <label class="btn btn-lg btn-block btn-primary font-weight-bold my-3 py-3" for="submit-form" id="form-button">
                            Place Order
                        </label>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Checkout End -->

{% endblock content %}

store/templates/store/create_product.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Add Product{% endblock title %}

{% block content %}
{% include 'messages.html' %}
<div class="errors" style="margin-left: 2rem;">
    {% for field in add_product_form %}
        <p>
        {% for error in field.errors %}
            <p style="color: rgb(175, 23, 23);">{{field.label_tag}} {{error}}</p>
        {% endfor %}
        </p>
    {% endfor %}

    {% if add_product_form.non_field_errors %}
        <div style="color: rgb(175, 23, 23);">
            {{add_product_form.non_field_errors}}
        </div>
    {% endif %}
</div>
<link rel="stylesheet" href="{% static 'css/jupyter-pattern.css' %}">
<div class="w-100 mx-auto bg-white" style="padding: 2rem 1rem;margin-bottom: 5rem;color: black;">
    <h2 style="text-align: center; margin-bottom: 4rem">Want to sell a product?</h2>
    <form method="post" action="{% url 'add-product' %}" enctype="multipart/form-data">
        {% csrf_token %}

        {{add_product_form.product_categories.label_tag}}
        {{add_product_form.product_categories}}

        <div style="display: flex; flex-direction: column; margin-bottom: 1rem;margin-top: 1rem">
            <label for="id_product_name">Product name</label>
            <input type="text" name="product_name" id="id_product_name">
        </div>

        <div style="display: flex; flex-direction: column; margin-bottom: 1rem;">
            <!-- PRICE -->
            <label for="id_product_price">Price</label>
            <input type="number" name="product_price" id="id_product_price" placeholder="In Naira(N)" step=".01">
        </div>

        <div style="display: flex; flex-direction: column; margin-bottom: 1rem;">
            <!-- SIZE -->
            <label for="">Size</label>
            <!-- <div style="margin-left: 1rem;"> -->
                {{ add_product_form.product_sizes }}

        </div>

        <div style="display: flex; flex-direction: column; margin-bottom: 1rem;">
            <label for="id_available_product">Number available</label>
            <input type="number" name="number_available" id="id_number_available">
        </div>

        <div style="display: flex; flex-direction: column; margin-bottom: 3rem;">
            <!-- COLOR -->
            <label for="product-color">Color</label>
            
            </select>
            {{ add_product_form.product_colors }}
        </div>

        <div style="display: flex; flex-direction: column; margin-bottom: 3rem;">
            <label for="id_discount">Discount</label>
            <small>(E.g 0-100, if no discount enter 0.)</small>
            <input type="number" name="discount" id="id_discount" placeholder="Value will be rendered in %">
        </div>

        <div style="display: flex; flex-direction: column; margin-bottom: 1rem;">
            <!-- Picture -->
            <p class="h5 mb-3">Product Image(s)</p>
            <div style="margin-bottom: 1rem;">
                <label for="id_product_image1">Image 1</label>
                <input type="file" name="product_image1" accept="image/png, image/gif, image/jpeg" id="id_product_image1">
            </div>
            <div style="margin-bottom: 1rem;">
                <label for="id_product_image2">Image 2</label>
                <input type="file" name="product_image2" accept="image/png, image/gif, image/jpeg" id="id_product_image2">
            </div>
            <div style="margin-bottom: 1rem;">
                <label for="product_image3">Image 3</label>
                <input type="file" name="product_image3" accept="image/png, image/gif, image/jpeg" id="id_product_image3">
            </div>
        </div>

        <textarea placeholder="Description" name="product_description" id="id_product_description" style="width: 100%;" rows="10" cols="5"></textarea>

        <button class="btn btn-primary" style="display: flex; margin: auto; margin-top: .5rem;width: 50%;" type="submit">
            <span style="margin: 0 auto;font-weight: bold;">Add Product</span>
        </button>
        <p style="color: green;text-align: center;" class="h5 mt-5">{{success}}</p>
    </form>
{% endblock content %}

store/templates/store/e.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>

store/templates/store/just_arrived.html
{% extends 'base.html' %}
{% block title %}Just Arrived{% endblock title %}
{% block content %}
    <div class="row px-xl-5 pb-3">
    {% for l_product in latest_products %}
        <div class="col-lg-4 col-md-6 col-sm-12 pb-1">
            {% include 'snippets/product_card.html' %}
        </div>
    {% endfor %}
    </div>
    {% include '../snippets/products_pagination_snippet.html' with p_products=latest_products %}
{% endblock content %}

store/templates/store/no_checkout.html
{% extends 'base.html' %}
{% block title %}No Checkout{% endblock title %}
{% block content %}
    <div class="container">
        <div class="d-flex flex-column">
            <p class="mx-auto text-dark">Your cart is empty. Nothing to checkout here!</p>
            <p class="mx-auto">
                <a href="{% url 'home' %}">
                    <button class="btn" style="background-color: #C17A74;color: white;padding: 1rem;">Start Shopping</button>
                </a>
            </p>
        </div>
    </div>


{% endblock content %}