Accounts/urls.py
from .views import vendor_reg_view, user_login_view, customer_reg_view, user_logout_view, must_auth
from django.urls import path

app_name = 'user'

urlpatterns = [
    path('v_reg/', vendor_reg_view, name='v_reg'),
    path('c_reg/', customer_reg_view, name='c_reg'),
    # path('v_login/', vendor_login_view, name='v_login'),
    path('login/', user_login_view, name="login"),
    path('logout/', user_logout_view, name='logout'),
    path('must_auth/', must_auth, name='must_auth')
]

E_commerce/urls.py
from re import template
from django.contrib import admin
from django.urls import path, include, reverse_lazy,re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from store.views import (
    delete_order_item, home_page, ContactView,
    ShopView, product_details,
    cart, checkout,
    add_product_view, quantity_increment,
    quantity_decrement, delete_order_item,
    # load_cities,
    no_cart, all_reviews,
    no_checkout, add_to_cart,
    get_product_queryset, review,
    vendor_dashboard, delete_product,
    vendor_product_detail, update_product,
    customer_dashboard, just_arrived,
    add_to_wishlist, remove_from_wishlist,
    wishlist, remove_from_wishlist_view,
    men_category,women_category,
    male_children_category, female_children_category,
    no_search, billing_address,
    make_payment, shop
    )
urlpatterns = [
    path('admin/', admin.site.urls),
    path("paystack", include(("paystack.frameworks.django.urls", 'paystack'),namespace='paystack')),
    path('', home_page, name='home'),
    path('shop/', shop, name='shop'),
    path('make-payment/', make_payment, name='make-payment'),
    path('add_to_cart/<product_id>/', add_to_cart, name='add_to_cart'),
    path('just_arrived_products/', just_arrived, name='just_arrived'),
    path('add_to_wishlist/<product_id>/', add_to_wishlist, name='add_to_wishlist'),
    path('remove_from_wishlist/<product_id>/', remove_from_wishlist, name='remove_from_wishlist'),
    # path('shop/', ShopDetailView.as_view(), name='shop'),
    path('<product_id>/product_details/', product_details, name='product_details'),
    path('wishlist/', wishlist, name='wishlist'),
    path('remove_from_wishlist_view/<product_id>', remove_from_wishlist_view, name='remove_from_wishlist_view'),
    path('search/', get_product_queryset, name="search"),
    path('no-search/', no_search, name="no_search"),
    path('<product_id>/reviews/', review, name="review"),
    path('vendor_dashboard/', vendor_dashboard, name='v_dashboard'),
    path('customer_dashboard/', customer_dashboard, name='c_dashboard'),
    path('billing_address/<transaction_id>/', billing_address, name='billing_address'),
    path('<product_id>/vendor_product_details/', vendor_product_detail, name='v_product_details'),
    path('<product_id>/update_product', update_product, name="update_product"),
    path('<product_id>/delete_product', delete_product, name="delete_product"),
    path('cart/', cart, name='cart'),
    path('all_reviews/<product_id>/', all_reviews, name='all_reviews'),
    path('men_category/', men_category, name='men_category'),
    path('women_category/', women_category, name='women_category'),
    path('male_children_category/', male_children_category, name='male_children_category'),
    path('female_children_category/', female_children_category, name='female_children_category'),
    path('cart/<item_id>/increment/', quantity_increment, name='q_incr'),
    path('cart/<item_id>/decrement/', quantity_decrement, name='q_decr'),
    path('cart/<item_id>/delete/', delete_order_item, name='del_item'),
    path('checkout/', checkout, name='checkout'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('add-product/', add_product_view, name='add-product'),
    path('users/', include('Accounts.urls')),
    # re_path(r'^update_item/$', updateItem, name='update_item'),
    path('no_cart/', no_cart, name='no_cart'),
    path('no_checkout', no_checkout, name='no_checkout'),
    # path('ajax/load-cities/', load_cities, name='ajax_load_cities'),

    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name="password/password_change_done.html"), name="password_change_done"),

    # path('password_change/', auth_views.PasswordChangeView.as_view(template_name='password/password_change.html'), name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name="password/password_reset_done.html"), name="password_reset_done"),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password/password_reset_complete.html'), name="password_reset_complete"),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='password/password_reset_form.html', 
        success_url = reverse_lazy('password_reset_complete'),
    ), name="password_reset_confirm"),    

    path('password_reset/', auth_views.PasswordResetView.as_view(
        template_name='password/password_reset.html',
        email_template_name='password/password_reset_email.html',
        subject_template_name='password/password_reset_subject.txt',
        success_url = reverse_lazy('password_reset_done'),
    ), name='password_reset'),
    
]




# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

paystack/frameworks/django/urls.py
import django

version = django.get_version().split(".")
if int(version[0]) >= 2:
    from django.urls import re_path as url
else:
    from django.conf.urls import url

from django.views.decorators.csrf import csrf_exempt

from . import settings
from . import views

urlpatterns = [
    url(
        r"^verify-payment/(?P<order>[\w.@+-]+)/$",
        views.verify_payment,
        name="verify_payment",
    ),
    url(
        r"^failed-verification/(?P<order_id>[\w.@+-]+)/$",
        views.failure_redirect_view,
        name="failed_verification",
    ),
    url(
        r"^successful-verification/(?P<order_id>[\w.@+-]+)/$",
        views.success_redirect_view,
        name="successful_verification",
    ),
    url(
        r"^failed-page/$",
        views.TemplateView.as_view(template_name="paystack/failed-page.html"),
        name="failed_page",
    ),
    url(
        r"^success-page/$",
        views.TemplateView.as_view(template_name="paystack/success-page.html"),
        name="success_page",
    ),
    url(r"^webhook/$", csrf_exempt(views.webhook_view), name="webhook"),
]

Accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, SetPasswordForm
from django.contrib.auth import authenticate
# from django.contrib.auth.models import User
from .models import Customer, Vendor, User
# from django.contrib.auth import get_user_model
# User = get_user_model()

class CustomerRegForm(UserCreationForm):
    """The form for Customers to register their accounts."""
    email = forms.EmailField(max_length=128, help_text="Provide a valid email address.")
    class Meta:
        model = Customer
        fields = ['fullname', 'username', 'address', 'first_phone_num', 'email','password1', 'password2', 'device']
    
    # def clean(self):
    #     if self.is_valid():
    #         email = self.cleaned_data.get('email').lower()
    #         password = self.cleaned_data.get('password')

    #         user = authenticate(email=email, password=password)
            
    #         users = User.objects.all()
    #         if user in users:
    #             raise forms.ValidationError(f"A similar user of the Customer user type already exist.")


class VendorRegForm(UserCreationForm):
    """The form for Customers to register their accounts."""
    email = forms.EmailField(max_length=128, help_text="Provide a valid email address.")
    class Meta:
        model = Vendor
        fields = ['fullname', 'username', 'address', 'first_phone_num', 'email','password1', 'password2', 'device']


class UserLoginForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput, label='Password')
    class Meta:
        model = User
        fields = ['email', 'password']

    def clean(self):
        if self.is_valid():
            email = self.cleaned_data['email'].lower()
            password = self.cleaned_data['password']
            user = authenticate(email=email, password=password)

            if not user:
                raise forms.ValidationError('Invalid login details')

# class VendorLoginForm(forms.ModelForm):
#     password = forms.CharField(widget=forms.PasswordInput, label='Password')
#     class Meta:
#         model = Vendor
#         fields = ['email', 'password']

#     def clean(self):
#         if self.is_valid():
#             email = self.cleaned_data['email'].lower()
#             password = self.cleaned_data['password']
#             user = authenticate(email=email, password=password)

#             if not user:
#                 raise forms.ValidationError('Invalid login details')

Accounts/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .forms import (
    CustomerRegForm, UserLoginForm, 
    VendorRegForm)
from .models import User
from store.models import Order, OrderItem
from phonenumber_field.phonenumber import PhoneNumber
from django.contrib import messages
import phonenumbers
# Create your views here.
def customer_reg_view(request):
    msg = None
    request.user.type = "CUSTOMER"
    if request.method == 'POST':
        form = CustomerRegForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            # print('Tephone: ', form.cleaned_data['first_phone_num'])
            raw_user = User.objects.get(device=request.session.get('device'))
            raw_user_orders = Order.objects.filter(customer=raw_user)
            raw_user.fullname=obj.fullname
            raw_user.username=obj.username
            raw_user.address=obj.address
            x = phonenumbers.parse(f"{obj.first_phone_num}", None)
            raw_user.first_phone_num=phonenumbers.format_number(x, phonenumbers.PhoneNumberFormat.INTERNATIONAL)
            raw_user.email=obj.email
            raw_user.device=obj.device
            raw_user.set_password(request.POST['password1'])
            raw_user.save()
            print('Orders', raw_user_orders)
            for raw_user_order in raw_user_orders:
                raw_user_order.customer.fullname=obj.fullname
                raw_user_order.customer.username=obj.username
                raw_user_order.customer.address=obj.address
                x = phonenumbers.parse(f"{obj.first_phone_num}", None)
                raw_user_order.customer.first_phone_num=phonenumbers.format_number(x, phonenumbers.PhoneNumberFormat.INTERNATIONAL)
                raw_user_order.customer.email=obj.email
                raw_user_order.customer.device=obj.device
                raw_user_order.save()
            form.device = request.session.get('device')
            # print('Form Device is: ', form.device)
            msg = 'Account created successfully'
            login(request, raw_user)
            request.session['device'] = []
            return redirect('home')
        else:
            msg = 'Form is Invalid!'
    else:
        form = CustomerRegForm()
    return render(request, 'Accounts/register.html', {
        'form': form, 
        'msg': msg, 
        })

def vendor_reg_view(request):
    msg = None
    request.user.type = "VENDOR"
    if request.method == 'POST':
        form = VendorRegForm(request.POST)
        if form.is_valid():
            form.save(commit=False)
            form.device = request.session.get('device')
            user = form.save()
            msg = 'Account created successfully'
            login(request, user)
            return redirect('add-product')
        else:
            msg = 'Form is Invalid!'
    else:
        form = VendorRegForm()
    return render(request, 'Accounts/register.html', {
        'form': form, 
        'msg': msg, 
        })

def user_login_view(request):
    form = UserLoginForm(request.POST or None)
    msg = None
    if request.method == 'POST':
        if form.is_valid():
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password')
            # username=form.cleaned_data.get('username')

            user = authenticate(email=email, password=password)

            if user is not None:
                login(request, user)
                # print(user.type)
                if user.type == "CUSTOMER":
                    try:    
                        cookie_order = Order.objects.get(customer__device=request.session.get('device'))
                    except:
                        pass
                    else:
                        try:
                            user_order, created = Order.objects.get_or_create(customer__email=email)
                        except:
                            user_order = Order.objects.filter(customer__email=email).order_by('-id').first()
                        # if len(user_order) > 0:
                        cookie_orderitems = cookie_order.orderitem_set.all()
                        user_orderitems = user_order.orderitem_set.all()
                        print('OrderITEM ARE: ', user_orderitems)
                        for item in cookie_orderitems:
                            new_item, created = OrderItem.objects.get_or_create(product=item.product, order=user_order, size=item.size, color=item.color)
                            if new_item.quantity == 0:
                                new_item.quantity = item.quantity
                            else:
                                new_item.quantity += item.quantity
                            new_item.size = item.size
                            new_item.color = item.color
                            new_item.save()
                        cookie_order.delete()
                        return redirect('home')
                    return redirect('home')
                elif user.type == "VENDOR":
                    return redirect('v_dashboard')
                # return redirect('checkout')
            # if user.type != "CUSTOMER":
            #     return HttpResponse('Sorry you do not have a Customer account with us.')
            else:
                msg = 'User does not exist.'
        else:
            msg = 'Validation Error'
    return render(request, 'Accounts/login.html', {
        'form': form,
        'msg': msg,
    })

# def vendor_login_view(request):
#     form = VendorLoginForm(request.POST or None)
#     msg = None
#     if request.method == 'POST':
#         if form.is_valid():
#             email = form.cleaned_data.get('email')
#             password = form.cleaned_data.get('password')
#             user = authenticate(email=email, password=password)

#             if user is not None:
#                 login(request, user)
#                 return redirect('add product')
#             # if user.type != "VENDORR":
#             #     return HttpResponse('Sorry you do not have a Vendor account with us.')
#             else:[[[[[[[[[[
#                 msg = 'User does not exist.'
#         else:
#             msg = 'Validation Error'
#     return render(request, 'Accounts/login.html', {
#         'form': form,
#         'msg': msg,
#     })

@login_required
def user_logout_view(request):
    logout(request)
    return redirect('home')
def must_auth(request):
    return render(request, 'Accounts/must_auth.html')

Accounts/templates/Accounts/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %}User Login{% endblock title %}

{% block content %}
<style>
    .form-group{
        margin: .3rem;
    }
</style>
    <div class="errors mb-2" style="margin-left: 2rem;">
        {% for field in form %}
            {% for error in field.errors %}
                <p style="color: rgb(175, 23, 23);">
                    {{error}}
                </p>
            {% endfor %}
        {% endfor %}

        {% if form.non_field_errors %}
            <div style="color: rgb(175, 23, 23);">
                {{form.non_field_errors}}
            </div>
        {% endif %}
    </div>
    <div class="content text-dark p-3 mx-auto">
        <h1 style="text-align: center;">Login</h1>
            <form action="" class="mb-4" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="email">Email: </label>
                <input type="email" class="form-control" id="email" name="email" placeholder="Enter your email" required>
            </div>
            <div class="form-group">
                <label for="password">Password: </label>
                <input type="password" class="form-control" id="password" name="password" placeholder="Enter your password" required>
            </div>

            <button class="px-5 py-2 text-light font-weight-semi-bold" style="background-color: #C5837C;margin-left: .3rem;">
                Login
            </button>
        </form>
        <p class="" style="margin-left: .3rem;">
            {% if request.user.type == "CUSTOMER" %}
                <a href="{% url 'user:c_reg' %}" class="text-dark">
                    Don't have an account? <span style="color: blue;">Register</span>
                </a>
            {% elif request.user.type == "VENDOR"%}
                <a href="{% url 'user:v_reg' %}" class="text-dark">
                    Don't have an account? <span style="color: blue;">Register</span>
                </a>
            {% endif %}
            
            <a href="{% url 'password_reset' %}" class="d-block mt-2" style="color: blue;">
                Forgot Password?
            </a>
        </p>
    </div>
{% endblock content %}

Accounts/templates/Accounts/must_auth.html
{% extends 'base.html' %}
{% block title %}Must be Authenticated{% endblock title %}
{% block content %}
    <div class="container">
        <div class="d-flex flex-column">
            <p class="mx-auto text-dark">Must be authenticated to view this page</p>
            <p class="mx-auto">
                <a href="{% url 'user:c_reg' %}" style="color: blue;">Customer Reg</a> OR <a href="{% url 'user:v_reg' %}" style="color: blue;">Vendor Reg</a> OR <a href="{% url 'user:login' %}" style="color: blue;">Login</a>
            </p>
        </div>
    </div>


{% endblock content %}

Accounts/templates/Accounts/register.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Vendor Registration{% endblock title %}

{% block content %}
    <style>
        .form-group {
            margin: .3rem;
        }
    </style>
    <div class="errors mb-2" style="margin-left: 2rem;">
        {% for field in form %}
            <p>
            {% for error in field.errors %}
                <p style="color: rgb(175, 23, 23);">{{field.label_tag}} {{error}}</p>
            {% endfor %}
            </p>
        {% endfor %}

        {% if form.non_field_errors %}
            <div style="color: rgb(175, 23, 23);">
                {{form.non_field_errors}}
            </div>
        {% endif %}
    </div>
    <div class="content text-dark p-3"> 
        <h1 style="text-align: center;">Register</h1>
        {% if request.user.type == "CUSTOMER" %}
            <form class="mb-4" method="POST" action="{% url 'user:c_reg' %}">
        {% elif request.user.type == "VENDOR" %}
            <form class="mb-4" method="POST" action="{% url 'user:v_reg' %}">
        {% endif %}
        
            {% csrf_token %}
                <div class="form-group">
                  <label for="fullname">Fullname</label>
                  <input type="text" class="form-control" id="fullname" aria-describedby="fullname" placeholder="Enter your fullname" name="fullname" >
                </div>
                <div class="form-group">
                  <label for="username">Username: </label>
                  <input type="text" class="form-control" id="username" name="username" placeholder="Enter your username" >
                </div>
                <div class="form-group">
                    <label for="address">Address: </label>
                    <input type="text" class="form-control" id="address" name="address" placeholder="Enter your address" >
                </div>
                <div class="form-group">
                    <label for="first_phone_num">Phone No 1: </label>
                    <input type="tel" class="form-control" id="first_phone_num" name="first_phone_num" placeholder="Enter your first phone number" >
                </div>
                <!-- <div class="form-group">
                    <label for="second_phone_num">Phone No 2: </label>
                    <input type="tel" class="form-control" id="second_phone_num" name="second_phone_num" placeholder="Enter your second phone number" >
                </div> -->
                <div class="form-group">
                    <label for="email">Email: </label>
                    <input type="email" class="form-control" id="email" name="email" placeholder="Enter your email" >
                </div>
                <div style="visibility: hidden;">
                    <!-- <label for="email">Email: </label> -->
                    <input type="text" class="form-control" id="device" name="device" placeholder="Device" value="{{ request.session.device }}">
                </div>
                <div class="form-group">
                    <label for="password1">Password 1: </label>
                    <input type="password" class="form-control" id="password1" name="password1" placeholder="Enter your password" >
                </div>
                <div class="form-group">
                    <label for="password2">Password 2: </label>
                    <input type="password" class="form-control" id="password2" name="password2" placeholder="Repeat your password" >
                </div>


            <button class="mt-4 px-5 py-2" style="background-color: #C5837C;margin-left: .3rem;" type="submit">
                Submit
            </button>
            <p class="text-center text-success">{{success_message}}</p>
        </form>
        <p style="margin-left: .3rem;">
        
        
        {% if request.user.type == "CUSTOMER" %}
        <a href="{% url 'user:login' %}" class="text-dark">
                Already have an account? <span style="color: blue;">Login</span>
        </a>
        {% elif request.user.type == "VENDOR" %}
        <a href="{% url 'user:login' %}" class="text-dark">
            Already have an account? <span style="color: blue;">Login</span>
        </a>
        {% endif %}
        </p>
    </div>
{% endblock content %}